web:
  build : .
  dockerfile : Dockerfile_web 
  ports:
    - 8888:80
  volumes:
    - ./code:/var/www/html
  container_name: web
  environment:
    - ENVIRONMENT=docker
  links:
    - db:mysql
    
db:
  build : .
  dockerfile : Dockerfile_db
  ports:
        - 3333:3306
  volumes:
    - ./mysql:/var/lib/mysql
  container_name: mysql
  environment:
    - ENVIRONMENT=docker
  env_file:
    - ./env/docker.env # environment-specific
